const KEY='smartStoreV1';const DAYS=['일','월','화','수','목','금','토'];
const defaults={store:{name:'LUMI NAIL',tagline:'당신의 일상에 작은 아름다움을',phone:'0212345678',address:'서울시 예시구 123',map:'https://map.naver.com/',staffLabel:'담당자',notice:'예약 전 휴무일과 담당자 일정을 확인해주세요.',introMode:'none',introMedia:'',staffEnabled:true},schedule:{open:'10:00',close:'20:00',slotMinutes:30,closedDays:[1],specialClosed:[{date:'2026-09-16',reason:'임시휴무'}]},services:[{id:'svc1',name:'원컬러',price:40000,duration:60,desc:'깔끔한 컬러 시술'},{id:'svc2',name:'프렌치',price:55000,duration:90,desc:'클래식 프렌치 스타일'},{id:'svc3',name:'케어',price:30000,duration:45,desc:'기본 손·발 케어'}],staff:[{id:'st1',name:'김원장',specialty:'아트 · 젤',services:['svc1','svc2','svc3'],daysOff:[2]},{id:'st2',name:'이실장',specialty:'프렌치 · 케어',services:['svc1','svc2','svc3'],daysOff:[4]}],reservations:[]};
function load(){try{return deepMerge(structuredClone(defaults),JSON.parse(localStorage.getItem(KEY)||'{}'))}catch{return structuredClone(defaults)}}function deepMerge(a,b){for(const k in b){if(b[k]&&typeof b[k]==='object'&&!Array.isArray(b[k])&&a[k])a[k]=deepMerge(a[k],b[k]);else a[k]=b[k]}return a}let data=load();const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];const save=()=>{localStorage.setItem(KEY,JSON.stringify(data));renderAll()};const money=n=>Number(n||0).toLocaleString('ko-KR')+'원';
function renderAll(){fillStore();renderServices();renderStaff();renderSchedule();renderReservations();$('#serviceCount').textContent=data.services.length;$('#staffCount').textContent=data.staff.length;const today=new Date().toISOString().slice(0,10);$('#todayReservations').textContent=data.reservations.filter(r=>r.date===today&&r.status!=='취소').length}
function fillStore(){$('#aStoreName').value=data.store.name;$('#aTagline').value=data.store.tagline;$('#aPhone').value=data.store.phone;$('#aAddress').value=data.store.address;$('#aMap').value=data.store.map||'';$('#aStaffLabel').value=data.store.staffLabel||'담당자';$('#aNotice').value=data.store.notice||'';$$('#introMode button').forEach(b=>b.classList.toggle('active',b.dataset.value===data.store.introMode));$('#staffEnabled').checked=!!data.store.staffEnabled}
$('#saveStore').onclick=()=>{Object.assign(data.store,{name:$('#aStoreName').value.trim(),tagline:$('#aTagline').value.trim(),phone:$('#aPhone').value.trim(),address:$('#aAddress').value.trim(),map:$('#aMap').value.trim(),staffLabel:$('#aStaffLabel').value.trim()||'담당자',notice:$('#aNotice').value.trim()});save()};
$('#introMode').onclick=e=>{const b=e.target.closest('button');if(!b)return;data.store.introMode=b.dataset.value;save()};$('#introFile').onchange=e=>{const f=e.target.files?.[0];if(!f)return;const max=7*1024*1024;if(f.size>max){alert('데모에서는 7MB 이하 파일을 사용해주세요.');return}const rd=new FileReader();rd.onload=()=>{data.store.introMedia=rd.result;data.store.introMode=f.type.startsWith('video')?'video':'image';save()};rd.readAsDataURL(f)};
$('#staffEnabled').onchange=()=>{data.store.staffEnabled=$('#staffEnabled').checked;save()};
function renderServices(){$('#adminServices').innerHTML=data.services.length?data.services.map(s=>`<article class="adminItem"><div><h3>${s.name}</h3><p>${money(s.price)} · ${s.duration}분 · ${s.desc||''}</p></div><button data-edit-service="${s.id}">편집</button></article>`).join(''):'<p class="formNote">등록된 서비스가 없습니다.</p>'}
function renderStaff(){$('#adminStaff').innerHTML=data.staff.length?data.staff.map(s=>`<article class="adminItem"><div><h3>${s.name}</h3><p>${s.specialty||''} · 휴무 ${s.daysOff?.map(d=>DAYS[d]).join('·')||'없음'}</p></div><button data-edit-staff="${s.id}">편집</button></article>`).join(''):'<p class="formNote">등록된 담당자가 없습니다.</p>'}
let editing={type:null,id:null};
function openEdit(type,id){editing={type,id};const isSvc=type==='service',obj=id?(isSvc?data.services:data.staff).find(x=>x.id===id):null;$('#editTitle').textContent=(obj?'편집':'추가')+' · '+(isSvc?'서비스':data.store.staffLabel);$('#editDelete').style.visibility=obj?'visible':'hidden';if(isSvc){$('#editFields').innerHTML=`<label class="field"><span>서비스명</span><input id="eName" value="${obj?.name||''}"></label><label class="field"><span>가격</span><input id="ePrice" type="number" inputmode="numeric" value="${obj?.price||0}"></label><label class="field"><span>소요시간(분)</span><input id="eDuration" type="number" inputmode="numeric" value="${obj?.duration||60}"></label><label class="field"><span>설명</span><input id="eDesc" value="${obj?.desc||''}"></label>`}else{$('#editFields').innerHTML=`<label class="field"><span>이름</span><input id="eName" value="${obj?.name||''}"></label><label class="field"><span>소개 / 전문분야</span><input id="eSpecialty" value="${obj?.specialty||''}"></label><div class="field"><span>가능 서비스</span><div id="eServices" class="chipList">${data.services.map(s=>`<label class="chip"><input type="checkbox" value="${s.id}" ${obj?.services?.includes(s.id)?'checked':''}> ${s.name}</label>`).join('')}</div></div>`}$('#editModal').classList.remove('hidden')}
function closeEdit(){$('#editModal').classList.add('hidden')}
$('#editClose').onclick=closeEdit;$('#addService').onclick=()=>openEdit('service',null);$('#addStaff').onclick=()=>openEdit('staff',null);document.addEventListener('click',e=>{const a=e.target.closest('[data-edit-service]');if(a)openEdit('service',a.dataset.editService);const b=e.target.closest('[data-edit-staff]');if(b)openEdit('staff',b.dataset.editStaff)});
$('#editSave').onclick=()=>{const isSvc=editing.type==='service',arr=isSvc?data.services:data.staff;let obj=editing.id?arr.find(x=>x.id===editing.id):{id:(isSvc?'svc':'st')+Date.now()};obj.name=$('#eName').value.trim();if(!obj.name)return;if(isSvc){obj.price=Number($('#ePrice').value||0);obj.duration=Number($('#eDuration').value||30);obj.desc=$('#eDesc').value.trim()}else{obj.specialty=$('#eSpecialty').value.trim();obj.services=[...$$('#eServices input:checked')].map(x=>x.value);obj.daysOff=obj.daysOff||[]}if(!editing.id)arr.push(obj);save();closeEdit()};
$('#editDelete').onclick=()=>{if(!editing.id)return;if(!confirm('삭제하시겠습니까?'))return;const arr=editing.type==='service'?data.services:data.staff;const i=arr.findIndex(x=>x.id===editing.id);if(i>=0)arr.splice(i,1);save();closeEdit()};
function renderSchedule(){$('#openTime').value=data.schedule.open;$('#closeTime').value=data.schedule.close;$('#slotMinutes').value=String(data.schedule.slotMinutes);$('#storeClosedDays').innerHTML=DAYS.map((d,i)=>`<label class="dayCheck"><input type="checkbox" value="${i}" ${data.schedule.closedDays.includes(i)?'checked':''}><span>${d}</span></label>`).join('');$('#specialClosedList').innerHTML=data.schedule.specialClosed.map((x,i)=>`<span class="chip">${x.date} ${x.reason||''}<button data-remove-special="${i}">✕</button></span>`).join('');$('#staffDaysOff').innerHTML=data.staff.map(st=>`<div class="staffSchedule"><h4>${st.name}</h4><div class="weekdayGrid">${DAYS.map((d,i)=>`<label class="dayCheck"><input type="checkbox" data-staff-day="${st.id}" value="${i}" ${st.daysOff?.includes(i)?'checked':''}><span>${d}</span></label>`).join('')}</div></div>`).join('')||'<p class="formNote">담당자를 먼저 등록해주세요.</p>'}
$('#saveSchedule').onclick=()=>{data.schedule.open=$('#openTime').value;data.schedule.close=$('#closeTime').value;data.schedule.slotMinutes=Number($('#slotMinutes').value);data.schedule.closedDays=$$('#storeClosedDays input:checked').map(x=>Number(x.value));data.staff.forEach(st=>st.daysOff=$$(`[data-staff-day="${st.id}"]:checked`).map(x=>Number(x.value)));save()};
$('#addSpecialClosed').onclick=()=>{const date=$('#specialClosedDate').value;if(!date)return;data.schedule.specialClosed.push({date,reason:$('#specialClosedReason').value.trim()});data.schedule.specialClosed=[...new Map(data.schedule.specialClosed.map(x=>[x.date,x])).values()].sort((a,b)=>a.date.localeCompare(b.date));$('#specialClosedDate').value='';$('#specialClosedReason').value='';save()};document.addEventListener('click',e=>{const b=e.target.closest('[data-remove-special]');if(b){data.schedule.specialClosed.splice(Number(b.dataset.removeSpecial),1);save()}});
function renderReservations(){const rs=[...data.reservations].sort((a,b)=>(a.date+a.time).localeCompare(b.date+b.time));$('#reservationList').innerHTML=rs.length?rs.map(r=>`<article class="adminItem"><div><h3>${r.date} ${r.time} · ${r.customerName}</h3><p>${r.serviceName} · ${r.staffName||'담당없음'} · ${money(r.price)}</p></div><span class="reservationStatus">${r.status}</span></article>`).join(''):'<p class="formNote">아직 예약이 없습니다.</p>'}
$$('.adminTabs button').forEach(b=>b.onclick=()=>{$$('.adminTabs button').forEach(x=>x.classList.toggle('active',x===b));$$('.adminPanel').forEach(p=>p.classList.toggle('active',p.dataset.panel===b.dataset.tab))});
renderAll();
